# Generated by Django 3.0.5 on 2020-04-29 18:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('date_acquired', models.DateTimeField(verbose_name='Date acquired')),
                ('euid', models.CharField(max_length=200, unique=True, verbose_name='External UID')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('date_acquired', models.DateTimeField(verbose_name='Date acquired')),
                ('euid', models.CharField(max_length=200, unique=True, verbose_name='External UID')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('date_experiment', models.DateTimeField(verbose_name='Date experiment')),
                ('disease', models.CharField(choices=[('MALARIA', 'Malaria'), ('DENGUE', 'Dengue'), ('CHIKUNGUNYA', 'Chikungunya'), ('COVID19', 'COVID19')], max_length=200, verbose_name='Disease')),
                ('concentration', models.FloatField(blank=True, help_text='The concentration of the microorganism in the sample.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Concentration (mmol/L)')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.Cartridge')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.Device')),
            ],
        ),
    ]
