# Generated by Django 3.0.5 on 2020-05-05 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('', 'Prefer not to say')], max_length=1, null=True, verbose_name='Gender')),
                ('dob', models.DateField(null=True, verbose_name='Date of birth')),
                ('postcode', models.CharField(max_length=8, null=True, verbose_name='Postcode')),
            ],
        ),
        migrations.CreateModel(
            name='TestingCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_type', models.CharField(choices=[('HOSP', 'Hospital'), ('CLIN', 'GP clinic'), ('DRIV', 'Drive through centre'), ('HOME', 'Home'), ('OTHR', 'Other')], max_length=4, verbose_name='Centre type')),
                ('lon', models.FloatField(verbose_name='Longitude')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('postcode', models.CharField(max_length=8, null=True, verbose_name='Postcode')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_test', models.DateTimeField(auto_now_add=True, verbose_name='Test date')),
                ('test_result', models.BooleanField(verbose_name='Test result')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Patient')),
                ('testing_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TestingCentre')),
            ],
        ),
    ]
