# Generated by Django 3.0.5 on 2020-05-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostictest',
            name='date_test',
            field=models.DateTimeField(verbose_name='Test date'),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='test_result',
            field=models.BooleanField(choices=[(True, 'Positive'), (False, 'Negative')], verbose_name='Test result'),
        ),
    ]
