# Generated by Django 3.0.5 on 2020-05-11 01:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200505_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingcentre',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='testingcentre',
            name='lon',
        ),
        migrations.AddField(
            model_name='testingcentre',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Coordinates'),
        ),
    ]
