# Generated by Django 3.0.5 on 2020-05-11 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200511_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingcentre',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='testingcentre',
            name='lon',
        ),
    ]
