# Generated by Django 3.0.5 on 2020-05-12 22:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200512_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='test_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Coordinates'),
        ),
    ]
