# Generated by Django 3.0.5 on 2020-05-13 01:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_patient_test_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_type', models.CharField(choices=[('HOSP', 'Hospital'), ('CLIN', 'GP clinic'), ('DRIV', 'Drive through centre'), ('HOME', 'Home'), ('OTHR', 'Other')], max_length=4, verbose_name='Centre type')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordinates')),
                ('postcode', models.CharField(max_length=8, null=True, verbose_name='Postcode')),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnostictest',
            name='centre_type',
        ),
        migrations.RemoveField(
            model_name='diagnostictest',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='diagnostictest',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='test_coordinates',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('X', 'Prefer not to say')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='testing_centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.TestingCentre'),
            preserve_default=False,
        ),
    ]
