# Generated by Django 3.0.5 on 2020-05-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_diagnostictest_raw_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
