# Generated by Django 3.0.5 on 2020-05-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200528_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostictest',
            name='raw_test_data',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Raw Test Data'),
        ),
    ]
